[project]
name = "longmove"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tomrutherford", email = "tmrutherford@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "trio>=0.30.0",
    "tomlkit (>=0.13.3,<0.14.0)",
    "platformdirs (>=4.4.0,<5.0.0)",
    "rich>=14.3.3",
]

[project.scripts]
lm = "longmove.main:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-trio>=0.8.0",
    "ruff>=0.12.4",
    "pytest-cov (>=7.0.0,<8.0.0)",
]

[tool.pytest.ini_options]
trio_mode = true

[tool.ruff.lint.isort]
force-single-line = true
